name: we_rate_dogs
description: A new Flutter project.




dev_dependencies:

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/WhiteRectangle.png
    - assets/login_logo.png
    - assets/shoes1.png
    - assets/drive-steering-wheel.jpg
    - assets/line.png
    - assets/collapsing_toolbar/logo.png
    - assets/plate/
    - assets/images/
    - assets/blurry_artist/
    - assets/buy_ticket/
    - assets/story/
    - assets/meeting/
    - assets/food_app/
    - assets/condo/
    - assets/audio/

  fonts:
    - family: Meeting-Icon
      fonts:
        - asset: assets/fonts/meeting/icomoon.ttf
    - family: SF-Pro-Text-Regular
      fonts:
          - asset: assets/fonts/story/SF-Pro-Text-Regular.otf

    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/fonts/story/SF-Pro-Text-Bold.otf

    - family: Calibre-Semibold
      fonts:
        - asset: assets/fonts/story/Calibre Semibold.otf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/story/custom_icons.ttf

    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Black.otf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf

    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          style: normal
    - family: icon
      fonts:
          - asset: assets/fonts/ico/icomoon.ttf

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.3.0"
  bottom_navy_bar: "^3.0.0"
  hidden_drawer_menu : 1.1.1
  flutter_inner_drawer: "^0.3.0"
  flutter_colorpicker: any
  flutter_markdown: 0.2.0
#  local_auth: 0.5.2+4

#  firebase_auth: ^0.11.1+6
#  cloud_firestore: ^0.12.5

  rxdart: ^0.21.0
  firebase_core: 0.4.0+8
  firebase_messaging: ^5.1.3
  synchronized : "^2.1.0+1"
  shimmer : "^1.0.0"
  flutter_slidable: "^0.5.3"
  http: ^0.12.0+1
  flutter_masked_text: ^0.8.0
  pull_to_refresh: ^1.5.3
  popup_menu: ^1.0.1
  simple_animations: 1.3.3
  wave: 0.0.8
  progress_hud: 1.1.0
  dotted_border: 1.0.2

  dio: ^2.1.7
  dio_http_cache: ^0.1.2
  fish_redux: ^0.2.5
  common_utils: ^1.1.1
  path_provider: ^1.1.0
  shared_preferences: ^0.5.3+1
  palette_generator: ^0.2.0

  url_launcher: ^5.0.3
  chewie: ^0.9.7
  video_player: 0.10.2
  youtube_extractor: ^1.0.2
  gzx_dropdown_menu: ^1.0.2
  intl: ^0.15.8
  cached_network_image: ^1.1.1
  parallax_image: ^0.3.1+1
 # flutter_staggered_grid_view: ^0.3.0
  collection: ^1.14.11
  photo_view: ^0.4.2
  loader_search_bar: ^1.0.3+3
  toast: ^0.1.5
  permission_handler: ^3.2.0
  webview_flutter: ^0.3.10+3
  screenshot: ^0.1.1
  share_extend: "^1.0.9"
  qr_flutter: ^2.1.0+55
  flutter_rating_bar: ^1.3.0+1
  flutter_swiper: ^1.1.6
  badges: ^1.1.0
  audioplayers: 0.13.1


  #   liquid_pull_to_refresh: ^1.1.1
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
